language: java

install: mvn -DpdiInstall=false -DpdiInstallDir=./target/pdi/plugins/steps/ic-riak-plugin -DskipTests=true -B -V clean
script: mvn -DpdiInstall=false -DpdiInstallDir=./target/pdi/plugins/steps/ic-riak-plugin test
# coveralls
# after_success: mvn clean cobertura:cobertura coveralls:cobertura
